### ISSUE TITLE
This method is not working on Chromium 57 or later

### ISSUE THREAD

**Issue by tonymiao2012** [kuscsik/gstreamer_pppapi#2]
Hi kuscsik,

Firstly thank you for sharing this example. You are appreciated!

However, I found this method was not working on Chromium 57. I used Linux based system and I tried to follow instructions under patch dir but could not even find papi_internal.gyp file in project. 

Any updates for latest Chromium? 

Tony

**Comment by zoltan-ongithub** [comment]
Hi @tonymiao2012 ,

unfortunately, I don't have the time to maintain this project for newer versions of Chromium. If you have any 
patches on the project, pull requests are welcome.

Zoltan

**Comment by tonymiao2012** [comment]
Hi kuscsik,

Thank you for your reply. Will close this issue cause I have no idea on how to use your method in latest Chrome project. Have a good one.

Tony
